import React from 'react';

const Amenities = {
    auto_lock: 'Auto Lock',
    security_system: 'Security System',
    lockbox: 'Lock box',
    fire_extinguisher: 'Fire Extinguisher',
    wifi: 'WIFI',
    pocket_wifi: 'Pocket Wifi',
    ac: 'A/C',
    heater: 'Heater',
    bath_essentials: 'Bath Essentials',
    hot_water: 'Hot Water',
    parking: 'Parking',
    tv: 'TV',
    dvd_player: 'DVD Player',
    sofa: 'Sofa',
    kitchen: 'Kitchen',
    oven: 'Oven',
    cooking_basics: 'Cooking Basics',
    eating_utensils: 'Eating Utensils',
    microwave: 'Microwave',
    refrigerator: 'Refrigerator',
    dish_washer: 'Dish Washer',
    dining_table: 'Dining Table',
    washer: 'Washer',
    dryer: 'Dryer',
    iron: 'Iron',
    crib: 'Crib',
    high_chair: 'High Chair',
    bath_tub: 'Bath Tub',
    washlet: 'Washlet',
    hairdryer: 'Hair Dryer',
};

export default Amenities;
