import Building from './building.js'
import FixedTermRentalContractBilingualAll from './fixed_term_rental_contract_bilingual_all'

const Base = FixedTermRentalContractBilingualAll;
// NOTE: imported into /contants/documents.js

const FixedTermRentalContractBilingualByPage = {
  // flat_building_name: { top: '204px', left: '-120px', component: 'input', borderColor: 'blue', size: 'medium' }
  // fieldset for inputs takes absolute positioning
  // fieldset form-group-document, takes params.top, params.left, params.width
  // Anything iside params needs to be in snake case eg input_type for use in rails api
  // !!!! Only height needs to be px NOT %
  // !!!add required: true for validation at submit
  1: {
    document_name: Base.document_name,
    name: Base.name,
    name_translation: Base.name_translation,
    address: Base.address,
    address_translation: Base.address_translation,
    flat_type: Base.flat_type,
    construction: Base.construction,
    floors: Base.floors,
    year_built: Base.year_built,
    units: Base.units,
    last_renovation_year: Base.last_renovation_year,
    unit: Base.unit,
    rooms: Base.rooms,
    layout: Base.layout,
    size: Base.size,
    balcony_size: Base.balcony_size,
    toilet: Base.toilet,
    bath_tub: Base.bath_tub,
    shower: Base.shower,
    wash_basin: Base.wash_basin,
    washer_dryer_area: Base.washer_dryer_area,
    hot_water: Base.hot_water,
    kitchen_grill: Base.kitchen_grill,
    parcel_delivery_box: Base.parcel_delivery_box,
    ac: Base.ac,
    lighting_fixed: Base.lighting_fixed,
    auto_lock: Base.auto_lock,
    cable_tv: Base.cable_tv,
    internet_ready: Base.internet_ready,
    mail_box: Base.mail_box,
    lock_key: Base.lock_key,
    key_number: Base.key_number,
    keys: Base.keys,
    power_usage_amount: Base.power_usage_amount,
    gas: Base.gas,
    water: Base.water,
    sewage: Base.sewage,
  }, // end of 1
  2: {
    parking_included: Base.parking_included,
    parking_spaces: Base.parking_spaces,
    parking_space_number: Base.parking_space_number,
    bicycle_parking_included: Base.bicycle_parking_included,
    bicycle_parking_spaces: Base.bicycle_parking_spaces,
    bicycle_parking_space_number: Base.bicycle_parking_space_number,
    motorcycle_parking_included: Base.motorcycle_parking_included,
    motorcycle_parking_spaces: Base.motorcycle_parking_spaces,
    motorcycle_parking_space_number: Base.motorcycle_parking_space_number,
    storage_included: Base.storage_included,
    storage_spaces: Base.storage_spaces,
    storage_space_number: Base.storage_space_number,
    dedicated_yard: Base.dedicated_yard,
    other_facility: Base.other_facility,
    other_facility_name: Base.other_facility_name,
    from_year: Base.from_year,
    from_month: Base.from_month,
    from_day: Base.from_day,
    to_year: Base.to_year,
    to_month: Base.to_month,
    to_day: Base.to_day,
    contract_length_years: Base.contract_length_years,
    contract_length_months: Base.contract_length_months,
    notice_from_year: Base.notice_from_year,
    notice_from_month: Base.notice_from_month,
    notice_from_day: Base.notice_from_day,
    notice_to_year: Base.notice_to_year,
    notice_to_month: Base.notice_to_month,
    notice_to_day: Base.notice_to_day,
    final_rent: Base.final_rent,
    payment_due_date: Base.payment_due_date,
    management_fees: Base.management_fees,
    fees_payment_due_date: Base.fees_payment_due_date,
    bank_name: Base.bank_name,
    bank_name_english: Base.bank_name_english,
    account_type: Base.account_type,
    account_number: Base.account_number,
    swift: Base.swift,
    account_name: Base.account_name,
    account_name_english: Base.account_name_english,
    transfer_fee_paid_by: Base.transfer_fee_paid_by,
    rent_payment_method: Base.rent_payment_method,
    final_deposit: Base.final_deposit,
    deposit_amount: Base.deposit_amount,
    facilities_usage_fee: Base.facilities_usage_fee,
    other_fees: Base.other_fees,
  },
  3: {
    owner_address: Base.owner_address,
    owner_address_translation: Base.owner_address_translation,
    owner_company: Base.owner_company,
    owner_company_translation: Base.owner_company_translation,
    owner_name: Base.owner_name,
    owner_name_translation: Base.owner_name_translation,
    owner_phone: Base.owner_phone,
    management_address: Base.management_address,
    management_address_translation: Base.management_address_translation,
    management_company: Base.management_company,
    management_company_translation: Base.management_company_translation,
    management_name: Base.management_name,
    management_name_translation: Base.management_name_translation,
    management_phone: Base.management_phone,
    management_registration_number_front: Base.management_registration_number_front,
    management_registration_number: Base.management_registration_number,
    flat_owner_address: Base.flat_owner_address,
    flat_owner_address_translation: Base.flat_owner_address_translation,
    flat_owner_company: Base.flat_owner_company,
    flat_owner_company_translation: Base.flat_owner_company_translation,
    flat_owner_name: Base.flat_owner_name,
    flat_owner_name_translation: Base.flat_owner_name_translation,
    flat_owner_phone: Base.flat_owner_phone,
    tenant_name: Base.tenant_name,
    tenant_age: Base.tenant_age,
    tenant_phone: Base.tenant_phone,
    co_tenant_name: Base.co_tenant_name,
    co_tenant_age: Base.co_tenant_age,
    co_tenant_name_1: Base.co_tenant_name_1,
    co_tenant_age_1: Base.co_tenant_age_1,
    co_tenant_name_2: Base.co_tenant_name_2,
    co_tenant_age_2: Base.co_tenant_age_2,
    co_tenants: Base.co_tenants,
    emergency_contact_address: Base.emergency_contact_address,
    emergency_contact_name: Base.emergency_contact_name,
    emergency_contact_phone: Base.emergency_contact_phone,
    emergency_contact_relationship: Base.emergency_contact_relationship,
    guarantor_address: Base.guarantor_address,
    guarantor_address_translation: Base.guarantor_address_translation,
    guarantor_name: Base.guarantor_name,
    guarantor_name_translation: Base.guarantor_name_translation,
    guarantor_phone: Base.guarantor_phone,
    guarantor_type: Base.guarantor_type,
    guarantor_registration: Base.guarantor_registration,
  },
  12: {
    contract_year: Base.contract_year,
    contract_month: Base.contract_month,
    contract_day: Base.contract_day,
    owner_address_1: Base.owner_address_1,
    owner_address_translation_1: Base.owner_address_translation_1,
    owner_name_1: Base.owner_name_1,
    owner_name_translation_1: Base.owner_name_translation_1,
    owner_phone_1: Base.owner_phone_1,
    tenant_address: Base.tenant_address,
    tenant_name_1: Base.tenant_name_1,
    tenant_phone_1: Base.tenant_phone_1,
    broker_registration_jurisdiction: Base.broker_registration_jurisdiction,
    broker_registration_jurisdiction_translation: Base.broker_registration_jurisdiction_translation,
    broker_registration_grantor: Base.broker_registration_grantor,
    broker_registration_front_number: Base.broker_registration_front_number,
    broker_registration_number: Base.broker_registration_number,
    broker_address_hq: Base.broker_address_hq,
    broker_address_hq_translation: Base.broker_address_hq_translation,
    broker_company_name: Base.broker_company_name,
    broker_company_name_translation: Base.broker_company_name_translation,
    broker_representative_name: Base.broker_representative_name,
    broker_representative_name_translation: Base.broker_representative_name_translation,
    broker_staff_registration_jurisdiction: Base.broker_staff_registration_jurisdiction,
    broker_staff_registration_jurisdiction_translation: Base.broker_staff_registration_jurisdiction_translation,
    broker_staff_registration: Base.broker_staff_registration,
    broker_staff_name: Base.broker_staff_name,
    broker_staff_name_translation: Base.broker_staff_name_translation,
  }
  //   1: {},
//   // end of page 1
//   2: {

//
//   }
  // end of page 2
};

export default FixedTermRentalContractBilingualByPage;
