// Object for configuring map markers according to category of place returned in gmaps
import supermarket from '../../assets/supermarket.png';
import school from '../../assets/school.png';
import convenienceStore from '../../assets/conveniencestore.png';
import subway from '../../assets/subway.png';
import train from '../../assets/train.png';
import gasStation from '../../assets/gasstation.png';

const googleBlueMarker = 'http://maps.google.com/mapfiles/ms/icons/blue.png';

const SearchTypeList = {
  accounting: { en: 'Accounting Offices', icon: googleBlueMarker, jp: '会計事務所' },
  airport: { en: 'Airports', icon: googleBlueMarker, jp: '空港' },
  amusement_park: { en: 'Amusement Parks', icon: googleBlueMarker, jp: 'アミューズメント施設' },
  aquarium: { en: 'Aquariums', icon: googleBlueMarker, jp: '水族館' },
  art_gallery: { en: 'Art Galleries', icon: googleBlueMarker, jp: 'アートギャラリー' },
  atm: { en: 'ATMs', icon: googleBlueMarker, jp: '銀行ATM' },
  bakery: { en: 'Bakeries', icon: googleBlueMarker, jp: 'パン屋' },
  bank: { en: 'Banks', icon: googleBlueMarker, jp: '銀行' },
  bar: { en: 'Bars', icon: googleBlueMarker, jp: 'バー' },
  beauty_salon: { en: 'Beauty Salons', icon: googleBlueMarker, jp: '美容室' },
  bicycle_store: { en: 'Bicycle Stores', icon: googleBlueMarker, jp: '自転車屋' },
  book_store: { en: 'Book Stores', icon: googleBlueMarker, jp: '本屋' },
  bowling_alley: { en: 'Bowling Alleys', icon: googleBlueMarker, jp: 'ボーリング場' },
  bus_station: { en: 'Bus Stations', icon: googleBlueMarker, jp: 'バス停車場' },
  cafe: { en: 'Cafes', icon: googleBlueMarker, jp: 'カフェ' },
  campground: { en: 'Campground', icon: googleBlueMarker, jp: 'キャンプ場' },
  car_dealer: { en: 'Car Dealers', icon: googleBlueMarker, jp: 'カーディーラー' },
  car_rental: { en: 'Car Rentals', icon: googleBlueMarker, jp: 'カーレンタル' },
  car_repair: { en: 'Car Repairs', icon: googleBlueMarker, jp: '車修理場' },
  car_wash: { en: 'Car Washes', icon: googleBlueMarker, jp: 'カーワッシュ' },
  casino: { en: 'Casinos', icon: googleBlueMarker, jp: 'カジノ' },
  cemetery: { en: 'Cemetaries', icon: googleBlueMarker, jp: '墓地' },
  church: { en: 'Churches', icon: googleBlueMarker, jp: '教会' },
  city_hall: { en: 'City Halls', icon: googleBlueMarker, jp: '市役所' },
  clothing_store: { en: 'Clothing Stores', icon: googleBlueMarker, jp: '服屋' },
  convenience_store: { en: 'Convenience Stores', icon: convenienceStore, jp: 'コンビニ' },
  courthouse: { en: 'Courthouse', icon: googleBlueMarker, jp: '裁判所' },
  dentist: { en: 'Dentists', icon: googleBlueMarker, jp: '歯科医院' },
  department_store: { en: 'Department Stores', icon: googleBlueMarker, jp: 'デパート' },
  doctor: { en: 'Doctors', icon: googleBlueMarker, jp: '医者' },
  electrician: { en: 'Electricians', icon: googleBlueMarker, jp: '電機修理' },
  electronics_store: { en: 'Electronics Stores', icon: googleBlueMarker, jp: '家電販売店' },
  embassy: { en: 'Embassies', icon: googleBlueMarker, jp: '大使館' },
  fire_station: { en: 'Fire Station', icon: googleBlueMarker, jp: '消防署' },
  florist: { en: 'Florists', icon: googleBlueMarker, jp: '花屋' },
  funeral_home: { en: 'Funeral Homes', icon: googleBlueMarker, jp: '葬儀場' },
  furniture_store: { en: 'Furniture Stores', icon: googleBlueMarker, jp: '家具販売店' },
  gas_station: { en: 'Gas Stations', icon: gasStation, jp: 'ガソリンステーション' },
  grocery_or_supermarket: { en: 'Grocery Stores', icon: supermarket, jp: '食料品店' },
  gym: { en: 'Gyms', icon: googleBlueMarker, jp: 'ジム' },
  hair_care: { en: 'Hair Care', icon: googleBlueMarker, jp: '美容室・美容用品' },
  hardware_store: { en: 'Hardware Stores', icon: googleBlueMarker, jp: 'ホームセンター' },
  hindu_temple: { en: 'Hindu Temples', icon: googleBlueMarker, jp: 'ヒンドゥー寺院' },
  home_goods_store: { en: 'Home Goods Stores', icon: googleBlueMarker, jp: '家庭洋品店' },
  hospital: { en: 'Hospitals', icon: googleBlueMarker, jp: '病院' },
  insurance_agency: { en: 'Insurance Agencies', icon: googleBlueMarker, jp: '保険販売' },
  jewelry_store: { en: 'Jewelry Stores', icon: googleBlueMarker, jp: 'ジュエリー店' },
  laundry: { en: 'Laundry', icon: googleBlueMarker, jp: 'クリーニング・コインランドリー' },
  lawyer: { en: 'Lawyers', icon: googleBlueMarker, jp: '弁護士事務所' },
  library: { en: 'Libraries', icon: googleBlueMarker, jp: '図書館' },
  liquor_store: { en: 'Liquor Stores', icon: googleBlueMarker, jp: 'リッカーストア' },
  local_government_office: { en: 'Local Government Offices', icon: googleBlueMarker, jp: '役所' },
  locksmith: { en: 'Locksmiths', icon: googleBlueMarker, jp: '錠前屋' },
  lodging: { en: 'Lodging', icon: googleBlueMarker, jp: 'ホテル・宿泊施設' },
  meal_delivery: { en: 'Meal Delivery', icon: googleBlueMarker, jp: '料理デリバリー' },
  meal_takeaway: { en: 'Meal Takeaway', icon: googleBlueMarker, jp: '料理テイクアウト' },
  mosque: { en: 'Mosques', icon: googleBlueMarker, jp: 'モスク' },
  movie_rental: { en: 'Movie Rentals', icon: googleBlueMarker, jp: 'ビデオレンタル' },
  movie_theater: { en: 'Movie Theaters', icon: googleBlueMarker, jp: '映画館' },
  moving_company: { en: 'Moving Companies', icon: googleBlueMarker, jp: '引越し業者' },
  museum: { en: 'Museums', icon: googleBlueMarker, jp: '美術館' },
  night_club: { en: 'Night Clubs', icon: googleBlueMarker, jp: 'ナイトクラブ' },
  painter: { en: 'Painters', icon: googleBlueMarker, jp: '塗装業者' },
  park: { en: 'Parks', icon: googleBlueMarker, jp: '公園' },
  parking: { en: 'Parking', icon: googleBlueMarker, jp: '駐車場' },
  pet_store: { en: 'Pet Stores', icon: googleBlueMarker, jp: 'ペットストア' },
  pharmacy: { en: 'Pharmacies', icon: googleBlueMarker, jp: '薬局' },
  physiotherapist: { en: 'Physiotherapists', icon: googleBlueMarker, jp: 'フィジオセラピスト' },
  plumber: { en: 'Plumbers', icon: googleBlueMarker, jp: '配管工' },
  police: { en: 'Police', icon: googleBlueMarker, jp: '警察署' },
  post_office: { en: 'Post Offices', icon: googleBlueMarker, jp: '郵便局' },
  real_estate_agency: { en: 'Real Estate Agencies', icon: googleBlueMarker, jp: '不動産業者' },
  restaurant: { en: 'Restaurants', icon: googleBlueMarker, jp: '飲食店' },
  roofing_contractor: { en: 'Roofing Contractors', icon: googleBlueMarker, jp: '屋根請負業者' },
  rv_park: { en: 'RV Parks', icon: googleBlueMarker, jp: 'RV パーク' },
  school: { en: 'Schools', icon: school, jp: '学校' },
  shoe_store: { en: 'Shoe Stores', icon: googleBlueMarker, jp: '靴屋' },
  shopping_mall: { en: 'Shopping Malls', icon: googleBlueMarker, jp: 'ショッピングモール' },
  spa: { en: 'Spas', icon: googleBlueMarker, jp: 'スパ' },
  stadium: { en: 'Stadiums', icon: googleBlueMarker, jp: 'スタジアム' },
  storage: { en: 'Storage', icon: googleBlueMarker, jp: '倉庫' },
  store: { en: 'Stores', icon: googleBlueMarker, jp: 'ストア' },
  subway_station: { en: 'Subway Stations', icon: subway, jp: '地下鉄駅' },
  supermarket: { en: 'Supermarkets', icon: supermarket, jp: 'スーパーマーケット' },
  synagogue: { en: 'Synagogues', icon: googleBlueMarker, jp: 'シナゴーグ' },
  taxi_stand: { en: 'Taxi Stands', icon: train, jp: 'タクシー乗り場' },
  train_station: { en: 'Train Stations', icon: googleBlueMarker, jp: '電車駅' },
  transit_station: { en: 'Transit Stations', icon: googleBlueMarker, jp: 'トランジットステーシェン' },
  travel_agency: { en: 'Travel Agencies', icon: googleBlueMarker, jp: '旅行代理店' },
  veterinary_care: { en: 'Veterinary Care', icon: googleBlueMarker, jp: '獣医師' },
  zoo: { en: 'Zoos', icon: googleBlueMarker, jp: '動物園' },
  point_of_interest: { en: 'Points of Interest', icon: googleBlueMarker, jp: 'ポイントオブインテレスト' },
  establishment: { en: 'Establishments', icon: googleBlueMarker, jp: '施設' },
  other: { en: 'Others', icon: googleBlueMarker, jp: 'その他' }
};

export default SearchTypeList;
