// import React from 'react';
import supermarket from '../../assets/supermarket.png';
import school from '../../assets/school.png';
import convenienceStore from '../../assets/conveniencestore.png';
import subway from '../../assets/subway.png';
import train from '../../assets/train.png';
import gasStation from '../../assets/gasstation.png';

const SearchTypeList = {
  accounting: { name: 'Accounting Offices', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  airport: { name: 'Airports', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  amusement_park: { name: 'Amusement Parks', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  aquarium: { name: 'Aquariums', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  art_gallery: { name: 'Art Galleries', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  atm: { name: 'ATMs', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  bakery: { name: 'Bakeries', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  bank: { name: 'Banks', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  bar: { name: 'Bars', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  beauty_salon: { name: 'Beauty Salons', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  bicycle_store: { name: 'Bicycle Stores', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  book_store: { name: 'Book Stores', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  bowling_alley: { name: 'Bowling Alleys', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  bus_station: { name: 'Bus Stations', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  cafe: { name: 'Cafes', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  campground: { name: 'Campground', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  car_dealer: { name: 'Car Dealers', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  car_rental: { name: 'Car Rentals', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  car_repair: { name: 'Car Repairs', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  car_wash: { name: 'Car Washes', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  casino: { name: 'Casinos', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  cemetery: { name: 'Cemetaries', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  church: { name: 'Churches', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  city_hall: { name: 'City Halls', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  clothing_store: { name: 'Clothing Stores', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  convenience_store: { name: 'Convenience Stores', icon: convenienceStore },
  courthouse: { name: 'Courthouse', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  dentist: { name: 'Dentists', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  department_store: { name: 'Department Stores', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  doctor: { name: 'Doctors', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  electrician: { name: 'Electricians', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  electronics_store: { name: 'Electronics Stores', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  embassy: { name: 'Embassies', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  fire_station: { name: 'Fire Station', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  florist: { name: 'Florists', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  funeral_home: { name: 'Funeral Homes', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  furniture_store: { name: 'Furniture Stores', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  gas_station: { name: 'Gas Stations', icon: gasStation },
  grocery_or_supermarket: { name: 'Supermarkets', icon: supermarket },
  gym: { name: 'Gyms', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  hair_care: { name: 'Hair Care', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  hardware_store: { name: 'Hardware Stores', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  hindu_temple: { name: 'Hindu Temples', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  home_goods_store: { name: 'Home Goods Stores', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  hospital: { name: 'Hospitals', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  insurance_agency: { name: 'Insurance Agencies', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  jewelry_store: { name: 'Jewelry Stores', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  laundry: { name: 'Laundry', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  lawyer: { name: 'Lawyers', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  library: { name: 'Libraries', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  liquor_store: { name: 'Liquor Stores', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  local_government_office: { name: 'Local Government Offices', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  locksmith: { name: 'Locksmiths', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  lodging: { name: 'Lodging', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  meal_delivery: { name: 'Meal Delivery', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  meal_takeaway: { name: 'Meal Takeaway', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  mosque: { name: 'Mosques', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  movie_rental: { name: 'Movie Rentals', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  movie_theater: { name: 'Movie Theaters', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  moving_company: { name: 'Moving Companies', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  museum: { name: 'Museums', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  night_club: { name: 'Night Clubs', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  painter: { name: 'Painters', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  park: { name: 'Parks', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  parking: { name: 'Parking', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  pet_store: { name: 'Pet Stores', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  pharmacy: { name: 'Pharmacies', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  physiotherapist: { name: 'Physiotherapists', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  plumber: { name: 'Plumbers', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  police: { name: 'Police', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  post_office: { name: 'Post Offices', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  real_estate_agency: { name: 'Real Estate Agencies', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  restaurant: { name: 'Restaurants', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  roofing_contractor: { name: 'Roofing Contractors', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  rv_park: { name: 'RV Parks', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  school: { name: 'Schools', icon: school },
  shoe_store: { name: 'Shoe Stores', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  shopping_mall: { name: 'Shopping Malls', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  spa: { name: 'Spas', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  stadium: { name: 'Stadiums', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  storage: { name: 'Storage', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  store: { name: 'Stores', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  subway_station: { name: 'Subway Stations', icon: subway },
  supermarket: { name: 'Supermarkets', icon: supermarket },
  synagogue: { name: 'Synagogues', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  taxi_stand: { name: 'Taxi Stands', icon: train },
  train_station: { name: 'Train Stations', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  transit_station: { name: 'Transit Stations', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  travel_agency: { name: 'Travel Agencies', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  veterinary_care: { name: 'Veterinary Care', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  zoo: { name: 'Zoos', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  point_of_interest: { name: 'Points of Interest', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  establishment: { name: 'Establishments', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' },
  other: { name: 'Others', icon: 'http://maps.google.com/mapfiles/ms/icons/blue.png' }
};

export default SearchTypeList;
