
const SearchTypeList = {
  accounting: 'Accounting Offices',
  airport: 'Airports',
  amusement_park: 'Amusement Parks',
  aquarium: 'Aquariums',
  art_gallery: 'Art Galleries',
  atm: 'ATMs',
  bakery: 'Bakeries',
  bank: 'Banks',
  bar: 'Bars',
  beauty_salon: 'Beauty Salons',
  bicycle_store: 'Bicycle Stores',
  book_store: 'Book Stores',
  bowling_alley: 'Bowling Alleys',
  bus_station: 'Bus Stations',
  cafe: 'Cafes',
  campground: 'Campground',
  car_dealer: 'Car Dealers',
  car_rental: 'Car Rentals',
  car_repair: 'Car Repairs',
  car_wash: 'Car Washes',
  casino: 'Casinos',
  cemetery: 'Cemetaries',
  church: 'Churches',
  city_hall: 'City Halls',
  clothing_store: 'Clothing Stores',
  convenience_store: 'Convenience Stores',
  courthouse: 'Courthouse',
  dentist: 'Dentists',
  department_store: 'Department Stores',
  doctor: 'Doctors',
  electrician: 'Electricians',
  electronics_store: 'Electronics Stores',
  embassy: 'Embassies',
  fire_station: 'Fire Station',
  florist: 'Florists',
  funeral_home: 'Funeral Homes',
  furniture_store: 'Furniture Stores',
  gas_station: 'Gas Stations',
  gym: 'Gyms',
  hair_care: 'Hair Care',
  hardware_store: 'Hardware Stores',
  hindu_temple: 'Hindu Temples',
  home_goods_store: 'Home Goods Stores',
  hospital: 'Hospitals',
  insurance_agency: 'Insurance Agencies',
  jewelry_store: 'Jewelry Stores',
  laundry: 'Laundry',
  lawyer: 'Lawyers',
  library: 'Libraries',
  liquor_store: 'Liquor Stores',
  local_government_office: 'Local Government Offices',
  locksmith: 'Locksmiths',
  lodging: 'Lodging',
  meal_delivery: 'Meal Delivery',
  meal_takeaway: 'Meal Takeaway',
  mosque: 'Mosques',
  movie_rental: 'Movie Rentals',
  movie_theater: 'Movie Theaters',
  moving_company: 'Moving Companies',
  museum: 'Museums',
  night_club: 'Night Clubs',
  painter: 'Painters',
  park: 'Parks',
  parking: 'Parking',
  pet_store: 'Pet Stores',
  pharmacy: 'Pharmacies',
  physiotherapist: 'Physiotherapists',
  plumber: 'Plumbers',
  police: 'Police',
  post_office: 'Post Offices',
  real_estate_agency: 'Real Estate Agencies',
  restaurant: 'Restaurants',
  roofing_contractor: 'Roofing Contractors',
  rv_park: 'RV Parks',
  school: 'Schools',
  shoe_store: 'Shoe Stores',
  shopping_mall: 'Shopping Malls',
  spa: 'Spas',
  stadium: 'Stadiums',
  storage: 'Storage',
  store: 'Stores',
  subway_station: 'Subway Stations',
  supermarket: 'Supermarkets',
  synagogue: 'Synagogues',
  taxi_stand: 'Taxi Stands',
  train_station: 'Train Stations',
  transit_station: 'Transit Stations',
  travel_agency: 'Travel Agencies',
  veterinary_care: 'Veterinary Care',
  zoo: 'Zoos',
  point_of_interest: 'Points of Interest',
  establishment: 'Establishments',
  other: 'Others'
};

export default SearchTypeList;
